"""Backend contracts: what ``MemoryEngine`` requires of its three stores.

These Protocols are the swap surface. ``MemoryEngine`` is constructed with a
database, a vector store, and a graph store (see ``engine.py`` and
``factory.build_engine``); each protocol here captures exactly the methods the
engine calls on one of them. An alternative backend (a different vector database,
a graph store that is not KuzuDB) is substitutable precisely when it satisfies
the matching protocol.

Why Protocols, not base classes: the contract is structural, so the concrete
stores (``db.Database``, ``vector.VectorStore``, ``graph.GraphStore``) satisfy
these without inheriting anything. Adding the contract changes no runtime
behavior; it only writes down the coupling that already exists.

Scope: this is the engine-facing surface, the union of ``self.db`` /
``self.vector`` / ``self.graph`` calls in ``engine.py``. The harness (daemon,
CLI, stats) reaches for a wider slice of the concrete stores and for backend
internals (``GraphStore._ensure_connected``, ``VectorStore._collection``); those
are not part of this contract and stay tied to the concrete implementations.

Enforcement: the protocols are ``runtime_checkable`` and ``tests/test_backends.py``
asserts each concrete store ``isinstance`` its protocol. That check is name-level
(it catches a backend missing a required method); signature compatibility is a
static concern for the day a type checker joins CI.

Optional collaboration points, deliberately left out of the required surface so a
minimal backend need not provide them:
  - The engine injects ``graph.description_scorer`` (a ``(query, texts) -> scores``
    callable) after construction to give the entity linker a description signal.
    A graph store without it simply runs the linker without that signal.
  - The engine reads ``vector.text_similarities`` via ``getattr(..., None)`` to
    feed that same signal. A vector store without it leaves the signal off.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from phileas.models import MemoryItem, Source


@runtime_checkable
class DatabaseBackend(Protocol):
    """The canonical store: memories, sources (sessions), proposals, the review queue.

    SQLite is the reference implementation (``db.Database``); the vector and graph
    stores are derived indexes rebuilt from what lives here.
    """

    # -- memories --
    def save_item(self, item: MemoryItem) -> None: ...
    def get_item(self, item_id: str) -> MemoryItem | None: ...
    def get_active_items(self) -> list[MemoryItem]: ...
    def get_items_by_type(self, memory_type: str) -> list[MemoryItem]: ...
    def get_items_by_id_prefix(self, prefix: str, limit: int = 10) -> list[MemoryItem]: ...
    def get_items_by_date_range(self, start_date: str, end_date: str | None = None) -> list[MemoryItem]: ...
    def update_item(self, item_id: str, content: str) -> MemoryItem | None: ...
    def archive_item(self, item_id: str, reason: str | None = None) -> None: ...
    def snapshot_item(self, item: MemoryItem) -> str: ...
    def search_by_keyword_scored(self, query: str, top_k: int | None = None) -> list[tuple[MemoryItem, float]]: ...
    def record_retrieval(self, item_id: str, retrieval_before: float, relevance: float) -> float: ...

    # -- sources (whole ingested sessions) --
    def save_source(self, source: Source) -> None: ...
    def get_source(self, source_id: str) -> Source | None: ...
    def get_source_by_client_key(self, client_key: str) -> Source | None: ...
    def get_ready_sources(self, limit: int = 20) -> list[Source]: ...
    def set_source_status(self, source_id: str, status: str) -> None: ...
    def mark_source_extracted(self, source_id: str, extracted_through: int) -> None: ...
    def reset_extracting_sources(self) -> list[str]: ...
    def source_status_counts(self) -> dict[str, int]: ...

    # -- provenance (memory <-> source sessions) --
    def add_memory_sources(self, memory_id: str, source_ids: list[str]) -> None: ...
    def get_source_ids_for_memory(self, memory_id: str) -> list[str]: ...
    def get_memories_for_source(self, source_id: str) -> list[MemoryItem]: ...

    # -- proposals / review queue --
    def save_proposal(
        self,
        proposal_id: str,
        content: str,
        memory_type: str = "knowledge",
        entities: list[dict] | None = None,
        relationships: list[dict] | None = None,
        source_text: str | None = None,
        source_id: str | None = None,
    ) -> None: ...
    def get_proposal(self, proposal_id: str) -> dict | None: ...
    def list_proposals(self, status: str | None = "pending", source_id: str | None = None) -> list[dict]: ...
    def update_proposal(self, proposal_id: str, fields: dict) -> None: ...
    def mark_proposal_resolved(self, proposal_id: str, status: str) -> None: ...

    # -- consolidation queue + reconciliation bookkeeping --
    def enqueue_consolidation(self, anchor: str, member_ids: list[str], span: tuple[str, str] | None) -> None: ...
    def add_reconcile_dismissal(self, a_id: str, b_id: str) -> None: ...
    def reconcile_dismissal_keys(self) -> set[str]: ...

    @staticmethod
    def reconcile_pair_key(a_id: str, b_id: str) -> str: ...

    # -- health / counts --
    def get_counts(self) -> dict: ...
    def storage_health(self, fading_threshold: float = 0.25) -> dict: ...


@runtime_checkable
class VectorBackend(Protocol):
    """Semantic index over memories and over session text.

    A derived index (ChromaDB in the reference implementation): searches return
    ``(id, similarity)`` pairs, never backend-native objects, so nothing about the
    underlying vector database leaks into the engine.
    """

    def add(self, memory_id: str, text: str, metadata: dict | None = None) -> None: ...
    def search(self, query: str, top_k: int | None = None) -> list[tuple[str, float]]: ...
    def get_embeddings(self, memory_ids: list[str]) -> dict[str, list[float]]: ...
    def delete(self, memory_id: str) -> None: ...
    def count(self) -> int: ...

    # -- sources collection (session text, keyed by source_id) --
    def add_source(self, source_id: str, text: str) -> None: ...
    def search_sources(self, query: str, top_k: int = 10) -> list[tuple[str, float]]: ...
    def source_count(self) -> int: ...


@runtime_checkable
class GraphBackend(Protocol):
    """Entity nodes and the typed edges between memories and entities.

    KuzuDB in the reference implementation. Identity is opaque (an entity id), so
    two things sharing a name can be distinct nodes and one thing with two names
    can be a single node. Methods speak in plain dicts and id strings.
    """

    # -- nodes / entities --
    def upsert_node(
        self,
        node_type: str,
        name: str,
        props: dict[str, Any] | None = None,
        description: str = "",
        context_neighbors: list[str] | None = None,
    ) -> str | None: ...
    def lookup_nodes(self, name_query: str) -> list[dict[str, Any]]: ...
    def search_nodes(self, name_query: str) -> list[dict[str, Any]]: ...
    def resolve_entity_id(self, id_or_prefix: str) -> str | None: ...
    def merge_entities(
        self, canonical_id: str, duplicate_ids: list[str], override_types: list[str] | None = None
    ) -> dict[str, Any]: ...
    def fold_entity_types(self) -> int: ...
    def get_related_entities(
        self, entity_type: str, entity_name: str, edge_type: str | None = None
    ) -> list[dict[str, Any]]: ...

    # -- edges --
    def create_edge(self, from_type: str, from_name: str, edge_type: str, to_type: str, to_name: str) -> None: ...
    def link_memory(
        self,
        memory_id: str,
        entity_type: str,
        entity_name: str,
        description: str = "",
        context_neighbors: list[str] | None = None,
    ) -> str | None: ...
    def link_memory_to_memory(self, from_id: str, edge_type: str, to_id: str) -> None: ...

    # -- memory <-> entity reads --
    def get_memories_about(self, entity_type: str, entity_name: str) -> list[str]: ...
    def get_entities_for_memory(self, memory_id: str) -> list[dict[str, str]]: ...
    def get_entities_for_memories(self, memory_ids: list[str]) -> dict[str, list[dict[str, str]]]: ...

    # -- roll-up (episode <-> gist) --
    def get_rollup_children(self, parent_id: str) -> list[str]: ...
    def get_rollup_parents(self, memory_ids: list[str]) -> dict[str, list[str]]: ...
    def get_rollup_indegree(self, memory_ids: list[str]) -> dict[str, int]: ...

    # -- scopes (memory holds only within a context) --
    def add_scope(
        self,
        memory_id: str,
        context: str,
        polarity: str = "holds",
        valid_from: Any = None,
        valid_to: Any = None,
        confidence: float | None = None,
    ) -> dict[str, Any]: ...
    def get_scopes_for_memory(self, memory_id: str) -> list[dict[str, Any]]: ...
    def get_scopes_for_memories(self, memory_ids: list[str]) -> dict[str, list[dict[str, Any]]]: ...
    def expand_context(self, name: str, hop_cap: int = 3) -> dict[str, Any] | None: ...

    # -- contradictions --
    def add_contradiction(
        self, from_id: str, to_id: str, resolution: str = "open", confidence: float | None = None
    ) -> dict[str, Any]: ...
    def get_contradictions_for_memory(self, memory_id: str) -> list[dict[str, Any]]: ...

    # -- reconciliation + stats --
    def reconciliation_rows(self, limit: int = 1000, sample_k: int = 3) -> list[dict[str, Any]]: ...
    def get_stats(self) -> dict[str, int]: ...


__all__ = ["DatabaseBackend", "VectorBackend", "GraphBackend"]
