"""Shared English stop-word list for recall paths.

Used by `engine.recall`'s legacy Path 3 graph word filter. Common function
words match almost every entity name; filtering them keeps the path precise
and stops importance/access tiebreakers from being dominated by false
positives.
"""

from __future__ import annotations

import re

STOP_WORDS: frozenset[str] = frozenset(
    {
        "a",
        "an",
        "the",
        "and",
        "or",
        "but",
        "in",
        "on",
        "at",
        "to",
        "for",
        "of",
        "with",
        "by",
        "from",
        "is",
        "it",
        "its",
        "be",
        "as",
        "that",
        "this",
        "was",
        "are",
        "were",
        "been",
        "have",
        "has",
        "had",
        "do",
        "did",
        "does",
        "will",
        "would",
        "could",
        "should",
        "may",
        "might",
        "shall",
        "can",
        "not",
        "no",
        "so",
        "if",
        "then",
        "than",
        "about",
        "us",
        "we",
        "i",
        "you",
        "he",
        "she",
        "they",
        "me",
        "him",
        "her",
        "them",
        "my",
        "our",
        "your",
        "his",
        "their",
        "still",
        "just",
        "also",
        "up",
        "out",
        "what",
        "which",
        "who",
        "when",
        "where",
        "how",
        "why",
        "between",
        "into",
        "through",
        "during",
        "before",
        "after",
        "while",
        "am",
        "any",
        "all",
        "both",
        "each",
        "few",
        "more",
        "most",
        "other",
        "same",
        "such",
        "own",
        "too",
        "very",
        "now",
        "remember",
    }
)


def strip_stopwords(text: str) -> str:
    """Return text with stop words removed; falls back to original if empty."""
    words_in = re.findall(r"\w+", text, flags=re.UNICODE)
    meaningful = [w for w in words_in if w.lower() not in STOP_WORDS and len(w) >= 2]
    return " ".join(meaningful) if meaningful else text
